### ISSUE TITLE
Tracking issue: new debugger features

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/mahboi#18]
Cool features of the debugger:

- Event view:
    - [x] Scrolling
    - [x] Filtering
- ASM view:
    - [x] Scrolling
    - [x] Set breakpoints by clicking on instruction
    - [ ] Show arrows to destination when hovering on jumping instructions
    - [x] Show comments with additional useful information (like when using an IO register: which register?)
- Manipulate data when debugger is paused
    - [ ] flags
    - [ ] registers
- Show more data:
    - [x] The stack
    - [x] PPU 
    - [ ] Sound
    - [x] Interrupt
    - [x] The whole memory (as popup presumably)
    - [ ] The last 10 addresses where we came across a jump-like instruction
- New ways to pause the emulator:
    - [x] Pass breakpoints via CLI
    - [ ] When a value somewhere (registers, memory, ...) has changed
    - [ ] When a specific instruction is executed
- More controls
    - [x] jump to end of function (run until RET or RETI reached)
    - [ ] run until any jumping instruction is reached
    - [ ] execute N instructions 
- [ ] Make data in CPU/PPU/... views bold (or something) if it changed in the last instruction

(*Feel free to edit this comment if you want to add new features*)

---

Note that this is a very extensive wish list and I doubt we will ever implement all of those (probably not even half of it).
